version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
  frontend:
    container_name: frontend
    image: service1frontend:latest
    build: ./service1frontend
  blackcards:
    container_name: blackcards
    image: service2blackcards:latest
    build: ./service2blackcards
  whitecards:
    container_name: whitecards
    image: service3whitecards:latest
    build: ./service3whitecards
  magicmaker:
    container_name: magicmaker
    image: service4magicmaker:latest
    build: ./service4magicmaker
