all:
  children:
    managers:
      hosts:
        docker-swarm-master:
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: '~/.ssh/id_rsa'
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    workers:
      hosts:
        docker-swarm-worker:
      vars:
      ansible_user: root
      ansible_ssh_private_key_file: '~/.ssh/id_rsa'
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        