- hosts: jenkins-vm
  become: true
  roles: 
  - docker
  - jenkins-vm

- hosts: managers
  become: true
  roles:
  - docker
  - swarm-manager

- hosts: workers
  become: true
  roles:
  - docker
  - swarm-worker