- hosts: jenkins-vm
  become: true
  roles: 
  - docker
  jenkins

- hosts: managers
  become: true
  roles:
  - docker
  swarmmanager

- hosts: workers
  become: true
  roles:
  - docker
  swarmworker

vars:
  app_repo: https://github.com/dkthecoder/Cards-Against-Humanity-Docker-Containers.git