- hosts: jenkins-vm
  become: true
  roles: 
  - docker
  - jenkins-vm

- hosts: managers
  become: true
  roles:
  - docker
  - swarm-manager

- hosts: workers
  become: true
  roles:
  - docker
  - swarm-worker

vars:
  app_repo: https://github.com/dkthecoder/Cards-Against-Humanity-Docker-Containers.git